<a href="https://colab.research.google.com/github/VBsaini/deepLearning-ZTM/blob/main/00_tesnsorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting infromation from tensors
* Manipulation tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular python function)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

# Introduction to Tensors

In [82]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [83]:
# Creating tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [84]:
# check number of dimensions of a tensor (ndim stands for number of dimension)
scaler.ndim

0

In [85]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [86]:
vector.ndim

1

In [87]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [88]:
matrix.ndim

2

In [89]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [90]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [91]:
tensor.ndim

3

# What we've created so far
* scalar: a single number.
* vector: a number with direction (e.g. wind speed with direction).
* matrix: a 2-dimensional array of numbers.
* tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

### Creating tensors with `tf.variable`

In [92]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [93]:
# Let's try change one of the elements in out changeable tensor
# changeable_tensor[0] = 7
# changeable_tensor

In [94]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random tensors
randoom tensors are tensors of some abitary size which contain random numbers

In [95]:
# Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [96]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does'nt effect the learning)

not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])

not_shuffled.ndim

2

In [97]:
 # Shuffle our non-shuffled tensor
tf.random.set_seed(23)
tf.random.shuffle(not_shuffled, 43)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### Other ways to make tensors

In [98]:
# Create a tensor of all one
tf.ones({3, 2})

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Turn NumPy into tensors
 Them main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [99]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [100]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [101]:
2*3*4

24

### Getting information from tensors
Attributes of tensors
* Shape
* Rank
* Axis or dimension
* Size

In [102]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [103]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [104]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimension (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimension (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


### Indexing tensors
 Tensors can be indexed just like python lists

In [105]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [106]:
# Get teh first element from the each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [107]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7], [3, 5], [8, 5]])
rank_2_tensor.ndim

2

In [108]:
# Get last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 5, 5], dtype=int32)>

In [109]:
# Add in extra dimension to our rant 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 5]],

       [[ 8],
        [ 5]]], dtype=int32)>

In [110]:
# Alternationve to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 5]],

       [[ 8],
        [ 5]]], dtype=int32)>

### Manipulation tensors (tensor operations)

**Basic operations**

`+` `-` `*` `/`

In [111]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [112]:
# Original tensor is not changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [113]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [114]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [115]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [116]:
# We can use the tensorflor built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [117]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix multiplications
in machine learining, matrix multiplicaion is one of the most common tensor operations.

There are 2 rules our tensors need to fulfill for multiplication

1. The inner dimensions must match
2. The resulting matrix has the shape of inner dimensions

In [118]:
# Matrix multiplication in tensorflow
t1 = tf.constant([[1,2,5], [7,2,1], [3,3,3]])
t2 = tf.constant([[3,5], [6, 7], [1,8]])
tf.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [119]:
# Matrix multiplication with python operator "@"
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [120]:
# change shape of tensor
tf.reshape(t2, shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [121]:
# Transpose
tf.transpose(t2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [122]:
tf.reshape(t2, shape=(6, 1)) # transpose and reshape are diff duh!!

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[3],
       [5],
       [6],
       [7],
       [1],
       [8]], dtype=int32)>

 **The dot product**

 Matrix multiplication is alo referred to as dot product

 you can perform matrix multiplicaion using:
 * `tf.matmul()`
 * `tf.tensordot()`
 * `@`

In [123]:
 # Perform the dot product on t1 and t2
tf.tensordot(t1, t2, 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

 Generally use transpose when you have diff shape

### Changeing the datatype of a tensor

In [124]:
# Create a tensor with default datatype (float32)
b = tf.constant([1.7,7.4])
c=tf.constant([1, 2])
b.dtype

tf.float32

In [125]:
 # Change from float 32 to float 16 (reduced pricision)
tf.cast(b, dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [126]:
# Change from int32 to float32
tf.cast(c, dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [127]:
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

### Aggregating tensors

Aggreagating tensor = condensing them from multiple values down to a smaller amount of values

In [128]:
# Get hte absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

let's go thorugh the following forms of aggregation:
* Min
* Max
* Mean
* Sum

In [129]:
# Create a random tensor with values b/w 0 nd 100 of size 50
E = tf.constant(np.random.randint(0, 100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([12, 21, 87, 10,  1, 16, 77, 70, 49, 66, 53, 41, 81, 96, 98, 63, 57,
       16,  5, 33, 57, 76, 49, 64, 84, 24, 69, 71, 37, 23, 77,  3, 14, 40,
       45, 59, 11, 55, 68, 96, 41,  6, 19, 99, 11, 62, 38, 75, 98, 75])>

In [130]:
tf.size(E).numpy(), E.shape, E.ndim,

(50, TensorShape([50]), 1)

In [131]:
# Min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [132]:
# Max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [133]:
# Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [134]:
# Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2498>

In [135]:
# Variance (idk why but did not work with int64)
D = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=859.55835>

In [136]:
# Standard deviation (idk why but did not work with int64)
tf.math.reduce_std(D)

<tf.Tensor: shape=(), dtype=float32, numpy=29.318226>

In [137]:
# Can also find variance with tfp
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=860>

### Find the positional maximum and minimum

In [138]:
# Create tensor for positional maximum and minimum
tf.random.set_seed(44)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
       0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
       0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
       0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
       0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
       0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
       0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
       0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
       0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
       0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ],
      dtype=float32)>

In [139]:
# Find positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [140]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9998728>

In [141]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9998728>

In [142]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [143]:
# Find positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=22>

In [144]:
F[tf.argmin(F)].numpy(), tf.reduce_min(F).numpy(), F[tf.argmin(F)] == tf.reduce_min(F)

(0.07325482, 0.07325482, <tf.Tensor: shape=(), dtype=bool, numpy=True>)

 ### Squeezing a tensor (removing all single dimensions)

In [145]:
# Create a tensor
tf.random.set_seed(44)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
           0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
           0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
           0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
           0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
           0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
           0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
           0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
           0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
           0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ]]]]],
      dtype=float32)>

In [146]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [147]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
       0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
       0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
       0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
       0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
       0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
       0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
       0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
       0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
       0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ],
      dtype=float32)>

In [148]:
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensors

In [149]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot necode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [150]:
tf.one_hot(some_list, depth=4, on_value="yallo", off_value="dudu")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yallo', b'dudu', b'dudu', b'dudu'],
       [b'dudu', b'yallo', b'dudu', b'dudu'],
       [b'dudu', b'dudu', b'yallo', b'dudu'],
       [b'dudu', b'dudu', b'dudu', b'yallo']], dtype=object)>

 ### Squaring, log, square root

In [151]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [152]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [153]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [154]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
Tensorflow interacts beautifully with Numpy arrays.


In [155]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [156]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [157]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [158]:
J.numpy()[0]

3.0

In [159]:
# The defaulT types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [160]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [161]:
!nvidia-smi

Tue Oct 15 17:58:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--